package fr.younesb.minijaja.lexer;

public enum TokenType {
    // DELIMITERS
    LEFT_PAR, RIGHT_PAR, LEFT_BRACK, RIGHT_BRACK, LEFT_BRACE, RIGHT_BRACE, SEMICOL, COMMA,

    // OPERATORS
    EQ, PLUS, PLUS_EQ, PLUS_PLUS, MINUS, STAR, SLASH, EQ_EQ, GREATER, AMPER_AMPER, PIPE_PIPE, BANG,

    // KEYWORDS
    CLASS, FINAL, MAIN, VOID, INT, BOOLEAN, IF, ELSE, WHILE, RETURN, TRUE, FALSE, LENGTH, WRITE, WRITELN,

    // LITERALS
    IDENT, INT_LITERAL, STRING_LITERAL,

    EOF
}